---
# https://hub.docker.com/r/rsyslog/syslog_appliance_alpine/
version: "3.9"
services:
  rsyslog:
    image: rsyslog/syslog_appliance_alpine:latest
    container_name: rsyslog
    environment:
      #- PUID=1000
      #- PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - ./log:/logs
      #- ./log:/var/log
      - ./etc/rsyslog.conf:/etc/rsyslog.conf
    ports:
      - 514:514/udp
      - 514:514/tcp
    restart: unless-stopped
